url: https://octokatt.github.io
baseurl: /mydrkevin/

# Site settings
title: Dr. Kevin
email: drkevin@weboflight.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Lightlines Publishing
  pic: 1
  position: Personal Growth and Enlightenment
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: pinterest
      url: #

- name: Web of Light
  pic: 2
  position: Non-profit Foundation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Spectrali
  pic: 3
  position: Spiritual Guidance
  social:
    - title: twitter
      url: #
    - title: youtube
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: pinterest
    url: 
  - title: linkedin
    url: 
  - title: youtube
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box Example 123
  - line: Somewhere, NH 03824

# Build settings
markdown: kramdown
permalink: pretty
